Feat/dynamic art
chingu-voyages/v33-bears-team-10 pull request #50
Opened 2021-10-16 19:16 UTC by Torja99

Uses user's top tracks to display changing album art on quiz selection page.
Closes #28 #43 #44

2021-10-19 11:54 UTC, angelopoole requested changes
Some changes need to be made, Test page shouldnt show up in actual development, or at least should be really hard to get to within normal means, 

eg a user might not know that the route '/juniper/testPage' even exists.

There's a personal todo file committed and pushed here "todo.org"

2021-10-19 11:54 UTC, angelopoole commented on hooks/useAuth.tsx
> +      console.log(fetchaAuth);
Remember to remove logs, at least when merging into main

2021-10-19 11:54 UTC, angelopoole commented on pages/index.tsx
> +        <TestPage />
‼️ Make sure testing pages are not visible to end users  ‼️

2021-10-19 11:54 UTC, angelopoole commented on todo.org
> +* TODO: hook up back end
You probably don't want to commit your personal todo file up to github

2021-10-20 13:16 UTC, Torja99 commented on hooks/useAuth.tsx
> +      console.log(fetchaAuth);
For sure forgot about this thanks!

2021-10-20 13:16 UTC, Torja99 commented on pages/index.tsx
> +        <TestPage />
oops forgot to remove

2021-10-20 13:16 UTC, Torja99 commented on todo.org
> +* TODO: hook up back end
Right removed it

2021-10-25 01:51 UTC, merged